# Generated by Django 5.0.7 on 2024-08-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_transaction_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='txbid',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='txn_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
